"""Grammar-based expression generator for constraint interaction analysis.

Sampling Distribution
---------------------
Expressions are generated by a stochastic process, NOT uniformly over all
valid expressions of depth ≤ d. The distribution is defined by:

  - At each internal node: 50/50 binary vs unary operator choice.
  - At each depth > 0: `leaf_probability` chance of early termination.
  - Leaf nodes: 50/50 variable vs constant.
  - Constants: uniform over [min, max], with 50% sign flip.

ρ(C) and M(i,j) are defined RELATIVE TO THIS DISTRIBUTION. Changing
leaf_probability or the binary/unary ratio changes the effective ρ values.
This is stated explicitly so that results are reproducible and the
distribution assumption is not hidden.
"""

import random
import yaml
import numpy as np
from sympy import sympify, SympifyError, Float


class GrammarGenerator:
    """Generates random mathematical expressions based on a specified grammar.

    This class parses the central `config.yaml` to extract the allowed variables,
    constants, binary operators, and unary operators. It then recursively builds
    mathematical expressions (ASTs) up to a maximum depth.

    Attributes:
        config (dict): The loaded grammar configuration dictionary.
        binary_ops (list[str]): List of allowed binary operators (e.g., '+', '-').
        unary_ops (list[str]): List of allowed unary operators (e.g., 'sin', 'cos').
        variables (list[str]): List of allowed terminal variables (e.g., 'x', 'y').
        constants_min (int): Minimum integer value for random constants.
        constants_max (int): Maximum integer value for random constants.
        max_depth (int): Maximum allowed depth for the generated expression tree.
        leaf_probability (float): Probability of returning a leaf at depth > 0.
        domain_validation_enabled (bool): Whether to numerically probe expressions.
        n_test_points (int): Number of random points for domain validation.
        test_range (list[float]): [lo, hi] range for domain validation points.
        rng (random.Random): Isolated random number generator instance.

    Example:
        >>> import pathlib
        >>> # Ensure config.yaml is present in the current working directory
        >>> gen = GrammarGenerator()
        >>> type(gen.binary_ops)
        <class 'list'>
    """

    def __init__(self, config_path="config.yaml"):
        """Initialize the GrammarGenerator.

        Args:
            config_path (str): The file path to the YAML configuration file.
                Defaults to "config.yaml".
        """
        # Load config — keep full config for monte_carlo access
        with open(config_path, "r") as f:
            self.config_root = yaml.safe_load(f)

        self.config = self.config_root["grammar"]

        self.binary_ops = self.config["operators"]["binary"]
        self.unary_ops = self.config["operators"]["unary"]
        self.variables = self.config["variables"]
        self.constants_min = self.config["constants"]["min"]
        self.constants_max = self.config["constants"]["max"]
        self.max_depth = self.config["max_depth"]
        self.leaf_probability = self.config.get("leaf_probability", 0.2)

        # Domain validation settings
        dv = self.config.get("domain_validation", {})
        self.domain_validation_enabled = dv.get("enabled", True)
        self.n_test_points = dv.get("n_test_points", 5)
        self.test_range = dv.get("test_range", [-10, 10])

        # Isolated Random State for Reproducibility
        seed = self.config_root.get("monte_carlo", {}).get("random_seed", None)
        self.rng = random.Random(seed)

        # Generation statistics — tracks rejections for convergence analysis
        self._stats = {
            "generated": 0,
            "sympify_failed": 0,
            "domain_rejected": 0,
            "returned_none": 0,
        }

    # ------------------------------------------------------------------
    # Statistics
    # ------------------------------------------------------------------

    @property
    def stats(self):
        """Return generation statistics (total generated, rejections by cause).

        Returns:
            dict: Dictionary with keys 'generated', 'sympify_failed',
                'domain_rejected', and 'returned_none'.

        Example:
            >>> gen = GrammarGenerator()
            >>> 'generated' in gen.stats
            True
        """
        return dict(self._stats)

    def reset_stats(self):
        """Reset all generation counters to zero.

        Example:
            >>> gen = GrammarGenerator()
            >>> gen.reset_stats()
            >>> gen.stats['generated'] == 0
            True
        """
        self._stats = {k: 0 for k in self._stats}

    # ------------------------------------------------------------------
    # Domain validation
    # ------------------------------------------------------------------

    def _validate_domain(self, expr):
        """Numerically evaluate expr at a few random points to catch domain errors.

        Why this exists: sympify(evaluate=False) preserves tree structure but
        never actually computes the expression, so things like division-by-zero,
        NaN, or complex results are never raised during parsing. This method
        does a quick numeric probe to catch those structural edge cases.

        Args:
            expr (sympy.Expr): The SymPy expression to validate.

        Returns:
            bool: True if all test points produce finite real values.
        """
        symbols = sorted(expr.free_symbols, key=str)
        if not symbols:
            # Constant expression — just check it's finite and real
            try:
                val = complex(expr)
                return bool(np.isfinite(val.real) and val.imag == 0)
            except (ValueError, TypeError, OverflowError):
                return False

        rng = np.random.default_rng(0)  # deterministic for reproducibility
        lo, hi = self.test_range
        for _ in range(self.n_test_points):
            subs = {s: Float(rng.uniform(lo, hi)) for s in symbols}
            try:
                val = complex(expr.subs(subs))
                if not (np.isfinite(val.real) and val.imag == 0):
                    return False
            except (ValueError, TypeError, ZeroDivisionError, OverflowError):
                return False
        return True

    # ------------------------------------------------------------------
    # Leaf generation
    # ------------------------------------------------------------------

    def _random_leaf(self):
        """Generate a random leaf node (variable or constant).

        Returns:
            str: A string representing either a variable name or a numeric constant.
        """
        if self.rng.random() < 0.5 and len(self.variables) > 0:
            return self.rng.choice(self.variables)
        else:
            val = self.rng.randint(self.constants_min, self.constants_max)
            # 50% chance of being negative for variety
            if val > 0 and self.rng.random() < 0.5:
                val = -val
            return str(val)

    # ------------------------------------------------------------------
    # Stochastic generation (original — depth ≤ max_depth)
    # ------------------------------------------------------------------

    def _generate_recursive(self, depth):
        """Recursively generate an expression string up to the given depth.

        At depth 0, always returns a leaf. At depth > 0, returns a leaf with
        probability `self.leaf_probability`, otherwise recurses with a random
        operator.

        Args:
            depth (int): The remaining depth allowed for the expression tree.

        Returns:
            str: A string representation of the generated mathematical expression.
        """
        if depth == 0:
            return self._random_leaf()

        if self.rng.random() < self.leaf_probability:
            return self._random_leaf()

        choice = self.rng.choice(["binary", "unary"])
        if choice == "binary" and len(self.binary_ops) > 0:
            op = self.rng.choice(self.binary_ops)
            left = self._generate_recursive(depth - 1)
            right = self._generate_recursive(depth - 1)
            return f"({left} {op} {right})"
        elif choice == "unary" and len(self.unary_ops) > 0:
            op = self.rng.choice(self.unary_ops)
            inner = self._generate_recursive(depth - 1)
            return f"{op}({inner})"
        else:
            return self._random_leaf()

    def generate(self, max_depth=None):
        """Generate a random mathematical expression as a string.

        Produces a tree with depth ≤ max_depth (stochastic — actual depth varies
        because of early leaf returns).

        Args:
            max_depth (int, optional): The maximum depth of the expression tree.
                If None, uses the max_depth specified in the configuration.

        Returns:
            str: The randomly generated mathematical expression.

        Example:
            >>> gen = GrammarGenerator()
            >>> expr_str = gen.generate(max_depth=2)
            >>> isinstance(expr_str, str)
            True
        """
        if max_depth is None:
            max_depth = self.max_depth
        return self._generate_recursive(max_depth)

    # ------------------------------------------------------------------
    # Exact-depth generation (for stratified sampling)
    # ------------------------------------------------------------------

    def _generate_exact_depth(self, depth, must_reach_target):
        """Recursively generate an expression with exact depth control.

        Why this exists: We need stratified sampling for density estimation
        (ensuring an equal number of samples at specific depths). A purely
        stochastic generator might rarely hit deep targets due to early leaf
        returns. This algorithm forces at least one branch to reach the
        target depth without early termination.

        Args:
            depth (int): Remaining depth.
            must_reach_target (bool): If True, this branch must reach depth 0
                without early termination.

        Returns:
            str: A string representation of the generated expression.
        """
        if depth == 0:
            return self._random_leaf()

        # Only allow early leaf return on branches that don't need to hit target
        if not must_reach_target and self.rng.random() < self.leaf_probability:
            return self._random_leaf()

        choice = self.rng.choice(["binary", "unary"])
        if choice == "binary" and len(self.binary_ops) > 0:
            op = self.rng.choice(self.binary_ops)
            # One child MUST reach target depth; the other is free
            forced = self._generate_exact_depth(depth - 1, must_reach_target=True)
            free = self._generate_exact_depth(depth - 1, must_reach_target=False)
            if self.rng.random() < 0.5:
                return f"({forced} {op} {free})"
            else:
                return f"({free} {op} {forced})"
        elif choice == "unary" and len(self.unary_ops) > 0:
            op = self.rng.choice(self.unary_ops)
            inner = self._generate_exact_depth(depth - 1, must_reach_target=True)
            return f"{op}({inner})"
        else:
            return self._random_leaf()

    def generate_at_depth(self, target_depth):
        """Generate an expression whose tree depth is exactly target_depth.

        Guarantees at least one root-to-leaf path has length == target_depth.

        Args:
            target_depth (int): The exact depth to produce.

        Returns:
            str: The generated expression string.

        Example:
            >>> gen = GrammarGenerator()
            >>> expr_str = gen.generate_at_depth(3)
            >>> isinstance(expr_str, str)
            True
        """
        return self._generate_exact_depth(target_depth, must_reach_target=True)

    # ------------------------------------------------------------------
    # SymPy conversion with validation
    # ------------------------------------------------------------------

    def generate_sympy(self, max_depth=None, max_retries=10):
        """Generate a valid SymPy expression (depth ≤ max_depth).

        Repeatedly calls `generate()` until a string is produced that
        successfully parses into a SymPy expression AND passes domain
        validation. Tracks rejection statistics.

        Args:
            max_depth (int, optional): The maximum depth of the expression tree.
            max_retries (int): The maximum number of generation attempts before
                giving up. Defaults to 10.

        Returns:
            sympy.Expr or None: A parsed SymPy expression object, or None if all
                retries failed.

        Example:
            >>> import sympy
            >>> gen = GrammarGenerator()
            >>> expr = gen.generate_sympy(max_depth=2)
            >>> isinstance(expr, sympy.Expr)
            True
        """
        for _ in range(max_retries):
            self._stats["generated"] += 1
            expr_str = self.generate(max_depth)
            try:
                # evaluate=False preserves tree structure for constraint checking
                expr_sympy = sympify(expr_str, evaluate=False)
            except (SympifyError, TypeError, ValueError, ZeroDivisionError):
                self._stats["sympify_failed"] += 1
                continue

            if self.domain_validation_enabled and not self._validate_domain(expr_sympy):
                self._stats["domain_rejected"] += 1
                continue

            return expr_sympy

        self._stats["returned_none"] += 1
        return None

    def generate_sympy_at_depth(self, target_depth, max_retries=10):
        """Generate a valid SymPy expression at exactly target_depth.

        Like generate_sympy, but uses generate_at_depth for stratified sampling.

        Args:
            target_depth (int): The exact tree depth to produce.
            max_retries (int): Maximum attempts. Defaults to 10.

        Returns:
            sympy.Expr or None: A parsed SymPy expression, or None.

        Example:
            >>> import sympy
            >>> gen = GrammarGenerator()
            >>> expr = gen.generate_sympy_at_depth(2)
            >>> isinstance(expr, sympy.Expr)
            True
        """
        for _ in range(max_retries):
            self._stats["generated"] += 1
            expr_str = self.generate_at_depth(target_depth)
            try:
                expr_sympy = sympify(expr_str, evaluate=False)
            except (SympifyError, TypeError, ValueError, ZeroDivisionError):
                self._stats["sympify_failed"] += 1
                continue

            if self.domain_validation_enabled and not self._validate_domain(expr_sympy):
                self._stats["domain_rejected"] += 1
                continue

            return expr_sympy

        self._stats["returned_none"] += 1
        return None

    # ------------------------------------------------------------------
    # Stratified sampling
    # ------------------------------------------------------------------

    def generate_stratified(self, depths=None, n_per_depth=None):
        """Generate expressions stratified equally across target depths.

        This implements equal samples per depth bucket (default: {2, 4, 6, 8}).

        Args:
            depths (list[int], optional): Depth buckets. Defaults to config.
            n_per_depth (int, optional): Samples per bucket. Defaults to N/len(depths).

        Returns:
            dict[int, list[sympy.Expr]]: Mapping from depth to list of expressions.

        Example:
            >>> gen = GrammarGenerator()
            >>> results = gen.generate_stratified(depths=[2, 4], n_per_depth=5)
            >>> len(results[2]) <= 5  # Can be less if retries fail
            True
            >>> 4 in results
            True
        """
        if depths is None:
            depths = self.config_root.get("monte_carlo", {}).get("depths", [2, 4, 6, 8])
        if n_per_depth is None:
            total_N = self.config_root.get("monte_carlo", {}).get("N", 100000)
            n_per_depth = total_N // len(depths)

        results = {}
        for d in depths:
            bucket = []
            for _ in range(n_per_depth):
                expr = self.generate_sympy_at_depth(d)
                if expr is not None:
                    bucket.append(expr)
            results[d] = bucket
        return results


if __name__ == "__main__":
    generator = GrammarGenerator()

    print("=== Stochastic generation (depth ≤ 4) ===")
    for i in range(5):
        expr = generator.generate_sympy(max_depth=4)
        print(f"  Sample {i + 1}: {expr}")

    print("\n=== Stats after stochastic generation ===")
    print(f"  {generator.stats}")

    generator.reset_stats()

    print("\n=== Exact-depth generation (depth == 3) ===")
    for i in range(5):
        expr = generator.generate_sympy_at_depth(3)
        print(f"  Sample {i + 1}: {expr}")

    print("\n=== Stats after exact-depth generation ===")
    print(f"  {generator.stats}")
